Technoblade isnt someone you would mess with.
type "/orphan"
"WHAT?"
"HERE?"
"WHERE?!"
"ya know, greek mythology has so- wait, WHERE?"
"Lemme get my orphan oblitorator.."
"Is there really an orphan?. I mean you keep saying it non-stop."
"WAIT THERE ACTUALLY IS,"
	"*slays orphan*"
"IM TRYING TO TALK ABOUT GREEK MYTHOLOGY HERE."
technoblade snaps when you say,  "/wheres your father?" 
"/arent you supposed to be in prison with dream?"
"IM NOT."
"MY DAD IS DEAD."
"LEAVE ME ALONE.."
